### ISSUE TITLE
[jre] update breaks pdfsam

### ISSUE THREAD

**Issue by R-a-l-f** [chaotic-aur/chaotic-aur.github.io#28]
Hi,

chaotic-aur/jre 21-1 breaks chaotic-aur/pdfsam 5.1.3-1.

Regards,
Ralf

**Comment by PedroHLC** [comment]
Hi Ralf, thanks for your report, but I'll sadly have to close this since you posted it in the wrong repo. This is the website's repo, packages issues must be filled in https://github.com/chaotic-aur/packages/issues/new/choose.

Also, I would like to bring to your attention that your issue may be invalid. In Arch Linux, when a Java application doesn't run with a specific runtime, you're supposed to switch to another runtime, they can co-exist: https://wiki.archlinux.org/title/Java#Switching_between_JVM
